# Generated by Django 4.2.3 on 2023-07-17 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='App_user',
        ),
    ]
