# Generated by Django 4.2.3 on 2023-07-19 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_alter_candidate_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='fileName',
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(default='Review', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidate.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.job')),
            ],
        ),
    ]
