# Generated by Django 4.2.3 on 2023-07-19 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_rename_jobdetails_job_description_job_position'),
        ('candidate', '0006_remove_resume_filename_job_status_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.job'),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
