# Generated by Django 4.2.3 on 2023-07-30 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_skill_experience_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='education',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
    ]
