# Generated by Django 4.2.3 on 2023-07-31 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_remove_resume_education_remove_resume_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.TextField(default='this is some description'),
            preserve_default=False,
        ),
    ]
