# Generated by Django 4.2.3 on 2023-08-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_alter_job_employer'),
        ('candidate', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='savedJobs',
            field=models.ManyToManyField(to='employer.job'),
        ),
    ]
