# Generated by Django 4.2.3 on 2023-07-16 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_joboffer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobOffer',
            new_name='Job',
        ),
    ]
