# Generated by Django 4.2.3 on 2023-07-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_rename_joboffer_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='position',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
