# Generated by Django 4.2.3 on 2023-07-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='graduation_Year',
            field=models.DateField(null=True),
        ),
    ]
