# Generated by Django 4.2.3 on 2023-07-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_resume_file_alter_resume_graduation_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(null=True, upload_to='files'),
        ),
    ]
