# Generated by Django 4.2.3 on 2023-07-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_alter_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='firstname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='lastname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
