# Generated by Django 4.2.3 on 2023-07-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_job_employer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='jobDetails',
            new_name='description',
        ),
        migrations.AddField(
            model_name='job',
            name='position',
            field=models.CharField(default='Bharggavbhai', max_length=255),
            preserve_default=False,
        ),
    ]
